main: main.c error.c scanner.c dynamic_string.c parser.c symtable.c expression.c table_stack.c code_gen.c
	gcc -o main main.c error.c scanner.c dynamic_string.c parser.c symtable.c expression.c table_stack.c code_gen.c -I.
